# Compile Size Optimizations
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no

# AUTO_SHIFT_ENABLE = yes
# SEND_STRING_ENABLE = yes
# COMBO_ENABLE = yes
# AUTOCORRECT_ENABLE = yes
# DYNAMIC_MACRO_ENABLE = yes
